variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-B --errors --show-version --fail-at-end"

image: maven:3-jdk-8

stages:
- build
- test
- coverage

cache:
  key: ${CACHE_VERSION}-dependencies
  paths:
  - .m2/repository

build:
  stage: build
  script: mvn $MAVEN_CLI_OPTS package -Dmaven.test.skip

unit-test:
  stage: test
  script: mvn test -B
  when: on_success

integration-test:
  stage: test
  services: &postgres_service
  - postgres:10
  variables: &postgres_variables
    POSTGRES_DB: gitlab_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: ""
  before_script: &copy_test_props
  - cp database/database-access/src/test/resources/gitlabci-test.properties database/database-access/src/test/resources/test.properties
  script: mvn $MAVEN_CLI_OPTS verify -Dtest=none -DfailIfNoTests=false
  when: on_success

test-coverage:
  stage: coverage
  services: *postgres_service
  variables: *postgres_variables
  cache:
    key: ${CACHE_VERSION}-coverage
    paths:
    - .m2/repository
    - ~/.sonar/cache
  before_script: *copy_test_props
  script:
  - mvn $MAVEN_CLI_OPTS verify -P coverage
  - echo TODO mvn $MAVEN_CLI_OPTS sonar:sonar -Psonar
  - echo TODO mvn $MAVEN_CLI_OPTS coveralls:report
  when: on_success
