language: java
jdk:
  - oraclejdk8
script: "mvn cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean test jacoco:report coveralls:report
notifications:
  slack:
    rooms:
      - kingsskiclub:BBL9dzzOo8JFgSqRupOaxr4p#software-integrations
    template:
      - "%{repository_slug} (%{commit}) to %{branch} by %{author} : %{result}"
      - "Build details: %{build_url}"
