language: java

jdk:
- oraclejdk8

sudo: false

addons:
  postgresql: "10"
  sonarcloud:
    organization: "andrewflbarnes-github"
    token:
      secure: "Td6s0n36tyq87zvJtgsdgvfC8RgNdLBvFGYGhB3cZvrt7qRqzP3Za3rC+DMiMi76+WZOKqUME6ybLM9ZltwamnrQGEuC93rOfcLYCt2z7m4hSBBb3IXZ9KTbI31QY2b0CeSoRz7yDT8JfVVM/EqR6r8X8Cs0rav8BIlsLfkZ/hQ2vTWLu7KjSuPcAHmxeBFqV/hMqBAaKhLXZXSrypSWGQb/xUkDOQYdJVNCzUNOSoPv3p3HyA+d78JAJUo9lx4iUuST0Y6zaiNwfDJcSVST8oXBKlQI6eGjxh9S7Q4NBucYubdTBwifYywOQRO4NCBLyZK/933I//QPHJIAUG1mQdCeQqecIn1tZL63SvwqjQlLDnXyHNBDQ1GVonTxME57h6jJU3Rbwpv2QBILWgBwnrMXuzcGypabL9/oDnG+pQTnX5EXRq+gyEIzq1FeA9rueqNFTwjmKmy6AguKX0eP9M/aRRo0bPEHVqOVP5o8kuMT8k+QJ2zxexUNnZwHZLevl0WjU9tUTVW9fuZCCBgPLv8G/R182xfikpHzf8XLza/svIyu9HgkDPaBFWA81Bt6ciAlFQvyzzpbhImP/XZMGxymIvZ92ys1dec56VDHIlI9sEJ0NpsN/DIi9plEOkJCAvYZcAO/wUnilA6LbZzwybGYAlSjnbACedJtcUVTPIg="
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

env:
  global:
  - PGPORT=5433

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache

notifications:
  email: false
  slack:
    rooms:
    - kingsskiclub:BBL9dzzOo8JFgSqRupOaxr4p#software-integrations
    template:
    - '%{repository_slug} (%{commit}) to %{branch} by %{author} : %{result}'
    - 'Build details: %{build_url}'

install: true

before_script:
# FIXME-travis-postgres: see https://github.com/travis-ci/travis-ci/issues/8537
- sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
# Use 9.6 auth config:
- sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
- sudo service postgresql restart
- cp database/database-access/src/test/resources/travis-test.properties database/database-access/src/test/resources/test.properties

script:
- mvn clean install -Dmaven.test.skip

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: mvn test
    - name: "Integration Tests"
      script: mvn verify -Dtest=none -DfailIfNoTests=false
    - stage: "Coverage"
      name: "SonarCloud"
      after_success: mvn -P coverage-sonar,postgres
    - name: "Coveralls"
      after_success: mvn -P coverage-coveralls,postgres
