language: java
jdk:
  - oraclejdk8
notifications:
  slack:
    rooms:
      - kingsskiclub:BBL9dzzOo8JFgSqRupOaxr4p#software-integrations
    template:
      - "%{repository} (%{commit}) by ${author} : %{result}"
      - "Build details: %{build_url}"
