version: "3.5"
services:
  kaas-database:
    container_name: krs-kaas-database
    image: postgres:10
    ports:
    - "${db_port}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  kaas-database-admin:
    container_name: krs-kaas-database-admin
    image: dpage/pgadmin4
    ports:
    - "9000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: andrewflbarnes@hotmail.co.uk
      PGADMIN_DEFAULT_PASSWORD: postgres

  kaas-backend:
    container_name: krs-kaas-backend
    image: andrewflbarnes/kaas-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - "${results_service_port}:8080"
    volumes:
    - "./docker/application.properties:/app/application.properties"
    - "./docker/database.properties:/app/database.properties"
    depends_on:
      - kaas-database

networks:
  default:
    name: krs
