version: "3"
services:
  postgres10:
    image: postgres:10
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  pgadmin:
    image: dpage/pgadmin4
    ports:
    - "9000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: andrewflbarnes@hotmail.co.uk
      PGADMIN_DEFAULT_PASSWORD: postgres
