version: 2
jobs:
  build:
    docker: &docker_default
      # specify the version you desire here
      - image: &build_image circleci/openjdk:8u171-jdk

    steps:
      - checkout
      - run: &copy_props cp database/database-access/src/test/resources/circleci-test.properties database/database-access/src/test/resources/test.properties
      - restore_cache: &restore_cache
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn package -B -Dmaven.test.skip

      - save_cache:
          paths:
          - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

  test:
    docker: *docker_default
    steps:
      - checkout
      - run: *copy_props
      - restore_cache: *restore_cache
      - run: mvn test -B

  integration-test:
    docker: &docker_integration
      - image: *build_image
      - image: postgres:10
    steps:
      - checkout
      - run: *copy_props
      - restore_cache: *restore_cache
      - run: mvn verify -Dtest=none -DfailIfNoTests=false -B

  coverage:
    docker: *docker_integration
    steps:
      - checkout
      - run: *copy_props
      - restore_cache: *restore_cache
      - run: mvn verify -P coverage -B
      - run: mvn sonar:sonar -P sonar -B
      - run: mvn coveralls:report -B

workflows:
  version: 2
  build_test_report:
    jobs:
      - build
      - test:
          requires:
            - build
      - integration-test:
          requires:
            - build
      - coverage:
          requires:
            - test
            - integration-test

